apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: dbs
  install:
    createNamespace: true
  chart:
    spec:
      chart: mongodb
      version: '10.30.8'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
