apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: services
  install:
    createNamespace: true
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 1m
